package com.epam.esm.exceptions;

public interface ExceptionErrorCode {

    String INCORRECT_ID = "40300";
    String INCORRECT_TAG_NAME = "40301";
    String INCORRECT_TAG_LENGTH = "40302";
    String INCORRECT_GIFT_CERTIFICATE_NAME = "40303";
    String INCORRECT_GIFT_CERTIFICATE_NAME_LENGTH = "40304";
    String INCORRECT_GIFT_CERTIFICATE_DESCRIPTION_LENGTH = "40304";
    String INCORRECT_GIFT_CERTIFICATE_PRICE = "40305";
    String INCORRECT_GIFT_CERTIFICATE_DURATION = "40305";
    String INCORRECT_TRANSFERRED_PARAMETERS = "40306";
}
