package com.epam.esm.exceptions;

public interface ExceptionErrorCode {

    String DATASOURCE_SAVING_ERROR = "404000";
    String DATASOURCE_NOT_FOUND = "404001";
    String DATASOURCE_NOT_FOUND_BY_PARAMETERS = "404002";
    String DATASOURCE_NOT_FOUND_BY_NAME = "404003";
    String DATASOURCE_NOT_FOUND_BY_ID = "404004";
    String CANNOT_FIND_GIFT_CERTIFICATE_TAGS = "404005";
    String CANNOT_DELETE_GIFT_CERTIFICATE_TAGS = "404006";
    String CANNOT_ADD_NEW_TAG = "404007";
}
